name: dart_clean_movies
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  dio: ^4.0.6
  intl: ^0.17.0
  dartz: ^0.10.1
  flutter_modular: ^5.0.0
  flutter_bloc: ^8.0.1
  
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.2.0
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/empty_svg.svg
